// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo6kPVpyGPI7pdwwfKjDxqs3qiAdNbfI0',
    appId: '1:350741960220:web:5c4ff4ba7b10dd7d1271d9',
    messagingSenderId: '350741960220',
    projectId: 'banco-c19d4',
    authDomain: 'banco-c19d4.firebaseapp.com',
    databaseURL: 'https://banco-c19d4-default-rtdb.firebaseio.com',
    storageBucket: 'banco-c19d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC35ocCsPaxK4eBlRjd2DghgQZeh27oZ58',
    appId: '1:350741960220:android:81a44ba419ab4f6c1271d9',
    messagingSenderId: '350741960220',
    projectId: 'banco-c19d4',
    databaseURL: 'https://banco-c19d4-default-rtdb.firebaseio.com',
    storageBucket: 'banco-c19d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs2PIw87mUWvOM_ctcpyGNbypKDcyUcrU',
    appId: '1:350741960220:ios:5a4dbb027a05e3901271d9',
    messagingSenderId: '350741960220',
    projectId: 'banco-c19d4',
    databaseURL: 'https://banco-c19d4-default-rtdb.firebaseio.com',
    storageBucket: 'banco-c19d4.appspot.com',
    iosClientId: '350741960220-brd9tnu4ia6pvp53ke82sp4sb36ett7b.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantecomigo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs2PIw87mUWvOM_ctcpyGNbypKDcyUcrU',
    appId: '1:350741960220:ios:1fa75d9b55621b031271d9',
    messagingSenderId: '350741960220',
    projectId: 'banco-c19d4',
    databaseURL: 'https://banco-c19d4-default-rtdb.firebaseio.com',
    storageBucket: 'banco-c19d4.appspot.com',
    iosClientId: '350741960220-8ce8cdn7r0e8nvtsmlq7v5f636uc7l5f.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantecomigo.RunnerTests',
  );
}
